# Generated by Django 4.0.2 on 2022-04-06 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CensoredWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('censored_word', models.TextField()),
                ('secret_word', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('first_posted_date', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_article', to='newsns.article')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CensoredWordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('censored_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwh_censored_word', to='newsns.censoredword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='censoredword',
            constraint=models.UniqueConstraint(fields=('censored_word', 'secret_word'), name='censored_word_unique'),
        ),
        migrations.AddField(
            model_name='article',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='censoredwordhistory',
            constraint=models.UniqueConstraint(fields=('user', 'censored_word'), name='censored_word_history_unique'),
        ),
    ]
