# Generated by Django 4.0.2 on 2022-04-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_article_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
